### ISSUE TITLE
responseRaw field is not accessible (1.2.2)

### ISSUE THREAD

**Issue by doggan** [merge-api/merge-hris-go#20]
@leewang0  Thanks for the addition of the `responseRaw` field to structs: https://github.com/merge-api/merge-hris-go/pull/19

Unfortunately this field is not accessible to users of this SDK because of the lower-case `r`. Lowercase field names are not exported outside of the package in Go: `eEmp.responseRaw undefined (cannot refer to unexported field or method responseRaw)`

![image](https://user-images.githubusercontent.com/517857/156671705-5976b34b-d6be-44be-822f-df11f7bfdd7e.png)

Can you please rename to `ResponseRaw` such that it's publicly accessible? Thanks.

**Comment by leewang0** [comment]
My apologies on this blunder, I'll have the PR up for this today.
